# EXTRA COLUMNS
---

You can extend an existing DataFrame with columns whose values depend on the values of already existing columns.

In [1]:
import pandas as pd

Imagine that the data contains the results of two tests of several students.

In [2]:
test_results = {'Test1':[84,37,55], 'Test2':[91,62,74]}
tests = pd.DataFrame(test_results)
tests.index = ['John Brown','Sarah Green','Peter Black']
tests

             Test1  Test2
John Brown      84     91
Sarah Green     37     62
Peter Black     55     74

You want to add a column that contains the sum of the points obtained.

In [3]:
tests['Total'] = tests['Test1'] + tests['Test2']
tests

             Test1  Test2  Total
John Brown      84     91    175
Sarah Green     37     62     99
Peter Black     55     74    129

### Tasks

To the test results, add a column containing the arithmetic mean of Test1 and Test2.

TypeError: 'list' object is not callable

The speed camera recorded the speeds of vehicles in km/h. The table below contains recorded speeds along with vehicle registration numbers.

Day    | KMH
-------|---------
BW3941 | 58
GM2309 | 76
WX1515 | 47
BB0099 | 50

1. Create a DataFrame containing the speed camera data.
1. Display the contents of the DataFrame
1. Add a 'Limit' column containing the permitted vehicle speed, i.e. 50 km/h
1. Display the contents of the DataFrame
1. Add a column in which calculate how many km/h each vehicle exceeded the speed limit
1. Display the contents of the DataFrame

In [25]:
speed_data = {"Day":["BW3941", "GM2309", "WX1515","BB0099"], "KMH":[58, 76, 47, 50]}

speed_df = pd.DataFrame(data=speed_data)

speed_df

      Day  KMH
0  BW3941   58
1  GM2309   76
2  WX1515   47
3  BB0099   50

In [28]:
speed_df["Limit"] = [50 for i in speed_df["Day"]]
speed_df

      Day  KMH  Limit
0  BW3941   58     50
1  GM2309   76     50
2  WX1515   47     50
3  BB0099   50     50

In [29]:
speed_df["Exceed"] = speed_df["KMH"] - speed_df["Limit"]
speed_df

      Day  KMH  Limit  Exceed
0  BW3941   58     50       8
1  GM2309   76     50      26
2  WX1515   47     50      -3
3  BB0099   50     50       0