# DATAFRAME
---

A DataFrame is a 2-dimensional data structure of rows and columns, similar to a spreadsheet.

## Creating DataFrame from Lists

You can create a DataFrame by adding columns in the data structure. Each column is created from a collection of data represented as a list.

In [1]:
import pandas as pd

In [2]:
#creating an empty DataFrame
company = pd.DataFrame()

# creating data collections as lists
company_months = ['January','February','March']
company_income = [23500,19700,31150]

# adding columns to DataFrame
company['Month'] = company_months
company['Income'] = company_income

# displaying DataFrame contents
company

      Month  Income
0   January   23500
1  February   19700
2     March   31150

### Tasks

Complete the data by adding the remaining months of the first half of the year and the income earned in these months. Then, display the data again.

In [3]:
company_months += ["March", "April", "May"]
company_income += [48967,48635,46537]

company

      Month  Income
0   January   23500
1  February   19700
2     March   31150

Display descriptive statistics for income earned.

In [4]:
company.describe()

             Income
count      3.000000
mean   24783.333333
std     5831.880772
min    19700.000000
25%    21600.000000
50%    23500.000000
75%    27325.000000
max    31150.000000

Display company income for the months of the second quarter.

In [5]:
company["Income"].tail(3)

0    23500
1    19700
2    31150
Name: Income, dtype: int64

Display descriptive statistics for the income earned in the months of the second quarter.

In [6]:
company["Income"].tail(3).describe()

count        3.000000
mean     24783.333333
std       5831.880772
min      19700.000000
25%      21600.000000
50%      23500.000000
75%      27325.000000
max      31150.000000
Name: Income, dtype: float64

## Creating DataFrame from 2D List

Instead of adding each column separately, you can create a DateFrame based on a two-dimensional (2D) list. Note that you will then need to add names to the columns you create.

In [9]:
# creating data collection as 2D list
company_data = [
    ['January',23500],
    ['February',19700],
    ['March',31150]
    ]

# creating DataFrame with column names
company = pd.DataFrame(data=company_data, columns=['Month','Income'])

# displaying DataFrame contents
company

      Month  Income
0   January   23500
1  February   19700
2     March   31150

### Tasks

The table below lists the university's students. 

StudentID | Name        | Surname      | Age | Program
----------|-------------|--------------|-----|-----------
902311    | Peter       | Red          | 21  | Accounting   
915027    | Sofia       | White        | 19  | Computer Science
900004    | Jack        | Grey         | 24  | Accounting
994031    | Mark        | Brown        | 22  | Engineering

Create a DataFrame using a 2D list. Then, display the contents of the DataFrame.

Calculate and display the average age of students.

## Creating DataFrame from Dictionary

As you know, a dictionary contains data consisting of key and value pairs of information, separated by a colon. Each pair of information represents one column in the DataFrame. The key is the name of the column and the value is the data collection (list). Below is an example of creating a DataFrame based on a dictionary.

In [ ]:
# creating data collection as a dictionary
company_data = {
    'Month':['January','February','March'],
    'Income':[23500,19700,31150]
    }

#creating DataFrame
company = pd.DataFrame(data=company_data)

#displaying DataFrame contents
company

### Tasks

Complete the DataFrame by adding a 'Tax' column along with the following values: 1200, 2350, 995. Then, display DataFrame contents.

Display descriptive statistics for the company income and tax.

## Creating DataFrame from File

Creating a DataFrame based on the data contained in a CSV file is incredibly simple. All you need to do is use the read_csv() function.

In [ ]:
sales = pd.read_csv('product_sales.csv')
sales

### Tasks

For sales data, calculate and display the average number of orders.

For sales data, calculate and display the total sales value.